// Для GitHub Pages используем моковые данные
export const SCRIPT_URL = '/delivery-tv/api'; // Будет возвращать тестовые данные

export const TRANSLATIONS = {
  RU: {
    title: 'Warehouse Dashboard',
    progress: 'Прогресс',
    next: 'Следующий',
    list: 'Список',
    status_active: 'АКТИВЕН',
    status_pause: 'ПАУЗА',
    status_wait: 'ОЖИДАНИЕ',
    eta_prefix: 'через ',
    delay_prefix: 'задержка ',
    lbl_start: 'Начало',
    victory: '🎉 ВСЕ ЗАДАНИЯ ВЫПОЛНЕНЫ!',
    empty: 'Заданий нет',
    nav_dashboard: 'Дашборд',
    nav_history: 'История',
    nav_plan: 'План',
    login_title: 'Вход',
    reg_title: 'Регистрация',
    btn_login: 'Войти',
    btn_reg: 'Зарегистрироваться',
    btn_cancel: 'Отмена',
    drv_title: 'Терминал оператора',
    btn_start: 'Старт',
    btn_finish: 'Завершить',
    menu_history: 'История задач',
    menu_logout: 'Выйти',
  },
  EN_CN: {
    title: '仓库仪表板',
    progress: 'Progress',
    next: 'Next',
    list: 'List',
    status_active: 'ACTIVE',
    status_pause: 'PAUSE',
    status_wait: 'WAITING',
    eta_prefix: 'ETA ',
    delay_prefix: 'Delay ',
    lbl_start: 'Start',
    victory: '🎉 ALL TASKS COMPLETED!',
    empty: 'No tasks',
    nav_dashboard: 'Dashboard',
    nav_history: 'History',
    nav_plan: 'Plan',
    login_title: 'Login',
    reg_title: 'Registration',
    btn_login: 'Login',
    btn_reg: 'Register',
    btn_cancel: 'Cancel',
    drv_title: 'Operator Terminal',
    btn_start: 'Start',
    btn_finish: 'Finish',
    menu_history: 'Task History',
    menu_logout: 'Logout',
  }
};
